name: sample-nas-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/
    - azure-ai-ml==1.5.0a20230215003
    - azure-storage-blob
    - azure-data-tables
    - azure-identity
    - azureml-mlflow
    - matplotlib
    - mldesigner
    - mlflow
    - torch
    - torchvision
    - torchaudio
    - "archai[dev] @ git+https://github.com/microsoft/archai.git"